language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  - rustup component add clippy

script:
  # fail when encountering warnings
  - cargo clippy --all-targets --all-features -- -D warnings
  # run tests
  - cargo test
